# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='personal_id_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
